// <auto-generated />
using System;
using Licenta.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Licenta.Migrations
{
    [DbContext(typeof(LicentaContext))]
    [Migration("20260223174209_SerieSasiu")]
    partial class SerieSasiu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Licenta.Models.Autovehicul", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CombustibilID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataITP")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRCA")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRevizie")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRovinieta")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kilometraj")
                        .HasColumnType("int");

                    b.Property<int?>("MarcaID")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NrInmatriculare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerieSasiu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CombustibilID");

                    b.HasIndex("MarcaID");

                    b.ToTable("Autovehicul");
                });

            modelBuilder.Entity("Licenta.Models.Combustibil", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TipCombustibil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Combustibil");
                });

            modelBuilder.Entity("Licenta.Models.Marca", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NumeMarca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("Licenta.Models.Autovehicul", b =>
                {
                    b.HasOne("Licenta.Models.Combustibil", "Combustibil")
                        .WithMany("Autovehicule")
                        .HasForeignKey("CombustibilID");

                    b.HasOne("Licenta.Models.Marca", "Marca")
                        .WithMany("Autovehicule")
                        .HasForeignKey("MarcaID");

                    b.Navigation("Combustibil");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Licenta.Models.Combustibil", b =>
                {
                    b.Navigation("Autovehicule");
                });

            modelBuilder.Entity("Licenta.Models.Marca", b =>
                {
                    b.Navigation("Autovehicule");
                });
#pragma warning restore 612, 618
        }
    }
}
